repos:
  - repo: https://github.com/PyCQA/isort
    rev: 7.0.0
    hooks:
      - id: isort
        name: isort (autofix)
        args: ['--profile=black']
        language_version: python3.12

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.14.5
    hooks:
      - id: ruff
        args: ['--fix']
        language_version: python3.12
      - id: ruff-format
        language_version: python3.12

  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.0.0a5
    hooks:
      - id: pylint
        language_version: python3.12
        args: ['--rcfile=pyproject.toml']

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        language_version: python3.12
        additional_dependencies: ['types-requests==2.32.4.20250913']
